Formvalidation
back-row/front-row pull request #82
Opened 2023-10-23 13:28 UTC by safstromo

2023-10-23 13:32 UTC, safstromo commented
![](https://github.trello.services/images/mini-trello-icon.png) [visa felmeddelande vid fel inloggning](https://trello.com/c/8cobK6NI/152-visa-felmeddelande-vid-fel-inloggning)

2023-10-23 13:32 UTC, safstromo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validera signup form](https://trello.com/c/5dK8WBYo/156-validera-signup-form)

2023-10-24 07:51 UTC, figgge requested changes

2023-10-24 07:51 UTC, figgge commented on src/components/LoginModal.vue
> +          }"
``
```suggestion

``

Do we need validation when logging in?

2023-10-24 08:52 UTC, figgge approved these changes
Great work!

2023-10-24 08:52 UTC, merged